name: Release

on:
  push:
    tags:
      - 'v*'
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  github-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for CHANGELOG
        id: cl
        run: |
          if [ -f CHANGELOG.md ]; then
            echo "has=true" >> "$GITHUB_OUTPUT"
          else
            echo "has=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Create release (with CHANGELOG)
        if: steps.cl.outputs.has == 'true'
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          generate_release_notes: true
          body_path: CHANGELOG.md

      - name: Create release (auto notes)
        if: steps.cl.outputs.has == 'false'
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          generate_release_notes: true

